# Configuraci贸n de Wrangler para Cloudflare Pages
name = "emotiontrack-frontend"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Configuraci贸n correcta para Cloudflare Pages
[build]
command = "npm run build && npm run export"
publish = "out"  # <-- CORREGIDO: Se quit贸 "frontend/"

# Variables de entorno para producci贸n
[env.production]
NEXT_PUBLIC_API_URL = "https://emotiontrack-backend.workers.dev"
NEXT_PUBLIC_AI_API_URL = "https://emotiontrack-ai.workers.dev"

# Variables de entorno para desarrollo/preview
[env.preview]
NEXT_PUBLIC_API_URL = "https://emotiontrack-backend-preview.workers.dev"
NEXT_PUBLIC_AI_API_URL = "https://emotiontrack-ai-preview.workers.dev"
