name = "emotiontrack-backend"
main = "src/index.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# Configuraci칩n para D1 (base de datos)
[[d1_databases]]
binding = "DB"
database_name = "emotiontrack-db"
database_id = "placeholder-id" # Esto se actualizar치 al crear la base de datos real

# Variables de entorno
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "cambiar-esto-en-produccion"

# Configuraci칩n de rutas
[routes]
pattern = "/api/*"
zone_name = "tu-dominio.com" # Actualizar con tu dominio real

# Configuraci칩n para desarrollo local
[dev]
port = 8787
